### ISSUE TITLE
矩阵题说明有问题

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#13]
**[app UI问题 – 没有解决。 学生版应加上说明 “以下25个自然数的顺序被打乱了，请你在规定时间内，按顺序从小到大点击相应的数字”. 老师版应采用同样的说明。]**

1.录入学生版后，进行学习状况测评最后会有一个25格的大表格，没有任何提醒是要学生干嘛    
    2.教师版中对于此表格的使用说明有问题，不是填入相应的字母，是“点击”                                                           功能性问题  
    复现步骤
     1.进入学生版学习状况测评  
     2.测评到最后一环节出现25宫格，不知道要干嘛，而且没有填写东西的地方
     期望结果
 栋辉备注：
在学生版，添加类似老师版的说明（注意先把说明修改正确。）
并添加说明“在完成此题后，请点击提交完成你的测评。”
     能有相关提示告知做什么？且完成后要提示接下来干什么？    
    问题提交人
    姜亚群
![image](https://cloud.githubusercontent.com/assets/19383704/15631624/9ec5d21e-25b6-11e6-8565-4e927276f293.png)

**Comment by c525225358** [comment]
这个不是解决了吗 请验证一下 图片发给你了
