### ISSUE TITLE
学生版老师版查看已解答的试卷，答案显示，图片显示不正确

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#3]
问题1：
老师版： 
b. 解答题的正确答案图片点击无法放大查看

学生版： （我测试的是 lisi@test.com)
b. 解答题的正确答案图片点击无法放大查看
c。解答题的正确答案图片获取错误 **（今天又重现了，简答题1的正确答案图片显示的是简答题2的答案图片，然后我杀掉app后，再次进入此页面，就显示正常了，难道图片也会缓存？这个可以解决吧？）**
bug图如下
![image](https://cloud.githubusercontent.com/assets/19383704/15649929/838b7186-26b8-11e6-8832-95ff9797ab7b.png)

问题提交人
栋辉

**Comment by c525225358** [comment]
解决
