### ISSUE TITLE
学生版今日作业安排输入开始时间 7：00 8：00 提示时间格式不对

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#43]
复现步骤
1. 学生版今日作业
2. 填写开始时间 “07：00”。。。
3.提交点击后，提示 时间格式不对，应该“00：00”，但是所填的已经是这个格式了

**Comment by c525225358** [comment]
这个没问题的呀。我这边ok 明天找个时间对一下

**Comment by c525225358** [comment]
我判断的是07:00这样，四位数 我这边看下

**Comment by c525225358** [comment]
HH:SS 这个标准格式，如果两种判断会出现问题，不能屏蔽
