### ISSUE TITLE
老师版填空题答案公式无法显示

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#54]
![0801 pic](https://cloud.githubusercontent.com/assets/19383704/17290652/eebd492a-5822-11e6-900d-e29768c33e8f.jpg)

问题描述
老师版，初三数学，一元二次方程的解，第五题
点击题目后显示的答案公式无法显示。 （m<\(\frac 1 4 \))

可以用zhaoting@chilaoshi.com 123456 登录查看

**Comment by c525225358** [comment]
已解决
