### ISSUE TITLE
查看试卷时app崩溃

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#57]
问题描述：
用 zhaoting@chilaoshi.com登录
试卷→初三试卷→进入学生已做完的试卷，点击， app崩溃

期望：
可查看试卷不崩溃

![1](https://cloud.githubusercontent.com/assets/19383704/17315947/59ebaf6c-58b3-11e6-9f7b-6c7aae0825fa.jpg)
![2](https://cloud.githubusercontent.com/assets/19383704/17315948/5a5ad392-58b3-11e6-8459-6c0e41818d0d.jpg)

**Comment by c525225358** [comment]
已解决
