### ISSUE TITLE
查看试卷题干图片时app崩溃

### ISSUE THREAD

**Issue by chilaoshi** [chilaoshi/test#58]
问题描述
用199345765@qq.com登录
考试中心，最后试卷"跨度阿利吉仑"，解答题第二题，点击查看图片，app崩溃

期望：
能正常查看题干图片

![3](https://cloud.githubusercontent.com/assets/19383704/17353795/74ae6f28-5986-11e6-9248-cf1a8ecad4b5.jpg)

**Comment by c525225358** [comment]
已解决
